 version: 2
 jobs:
   working_directory: ~/build/quixote
   build:
     docker:
       - image: willparr/quixote:latest
     steps:
       - checkout:
           path: ~/src/quixote
       - run:
           name: "Clone submodules"
           command: |
                git -C ~/src/quixote submodule init
                git -C ~/src/quixote submodule update --remote
       - run:
           name: "Building QXT"
           command: |
                cmake -G Ninja ~/src/quixote
