 version: 2
 jobs:
   build:
     docker:
       - image: willparr/quixote:latest
     working_directory: ~/build/quixote
     steps:
       - checkout:
           path: ~/src/quixote
       - run:
           name: "Clone submodules"
           command: |
                git -C ~/src/quixote submodule update --init --recursive
       - run:
           name: "Building QXT"
           command: |
                cmake -G Ninja ~/src/quixote && ninja    
       - run:
           name: "Executing tests"
           command: |
                export GTEST_OUTPUT=xml:/tmp/test-results/gtest/
                mkdir -p /tmp/test-results/gtest
                sudo ctest -T memcheck
       - store_test_results:
           path: /tmp/test-results   
       - store_artifacts:
           path: /tmp/test-results 
        
