 version: 2
 jobs:
   build:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run:
           name: "Clone submodules"
           command: |
                git submodule init
                git submodule update --remote
