 version: 2
 jobs:
   working_directory: ~/src
   build:
     docker:
       - image: willparr/quixote:latest
     steps:
       - checkout
       - run:
           name: "Clone submodules"
           command: |
                git submodule init
                git submodule update --remote
       - run:
           working_directory: ~/build/quixote
           name: "Building QXT"
           command: |
                cd ~/build/quixote
                cmake -G Ninja ~/src/quixote
