 version: 2
 jobs:
   build:
     docker:
       - image: circleci/ruby:2.4.1
     working_directory: ~/src
     steps:
       - checkout
       - run:
           name: "Clone submodules"
           command: |
                git submodule init
                git submodule update --remote
       - run: mkdir -p ~/build/quixote
       - run:
           name: "Building QXT"
           command: |
                cd ~/build/quixote
                cmake -G Ninja ~/src/quixote
