 version: 2
 jobs:
   build:
     docker:
       - image: willparr/quixote:latest
     working_directory: ~/build/quixote
     steps:
       - checkout:
           path: ~/src/quixote
       - run:
           name: "Clone submodules"
           command: |
                git -C ~/src/quixote submodule update --init --recursive
       - run:
           name: "Building QXT"
           command: |
                cmake -G Ninja ~/src/quixote && ninja
